# Internshala Scrapping

In [80]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [135]:
url = "https://internshala.com/internships/data-science-internship/"
data = requests.get(url).text

In [91]:
dictData = {"Title":[],"Company Name":[],"Location":[],"Start Date":[],"Duration":[],"Stipend":[]}

In [92]:
soup = BeautifulSoup(data,"html.parser")
for i in soup.select("h3.heading_4_5.profile"):
    dictData["Title"].append(i.get_text().strip())

In [93]:
for i in soup.select("div.company_and_premium"):
    dictData["Company Name"].append(i.get_text().strip())

In [94]:
for i in soup.select("div#location_names"):
    dictData["Location"].append(i.get_text().strip())

In [95]:
for i in soup.select("span.start_immediately_desktop"):
    dictData["Start Date"].append(i.get_text().strip())

In [126]:
rows = soup.find_all('div', class_='other_detail_item_row')

for row in rows:
    item_bodies = row.find_all('div', class_='item_body')
    for item_body in item_bodies:
        if 'Months' in item_body.get_text() or 'Weeks' in item_body.get_text():
            duration_text = item_body.get_text(strip=True)
            dictData["Duration"].append(i.get_text().strip())

In [97]:
for i in soup.select("span.stipend"):
    dictData["Stipend"].append(i.get_text().strip())

In [132]:
print(len(dictData["Title"]))
print(len(dictData["Company Name"]))
print(len(dictData["Location"]))
print(len(dictData["Start Date"]))
print(len(dictData["Duration"]))
print(len(dictData["Stipend"]))

40
40
40
40
40
40

In [134]:
df = pd.DataFrame(dictData)
df.to_csv("InternShala.csv",index=False,encoding='utf-8-sig')

# reading the file

In [137]:
data = pd.read_csv("InternShala.csv")
data

,Title,Company Name,Location,Start Date,Duration,Stipend
0,Artificial Intelligence (AI),FoodNEST(S) Technologies Private Limited,Lucknow,Immediately,"₹ 8,000 /month","₹ 4,000-8,000 /month"
1,Data Analytics,GoMechanic,Gurgaon,Immediately,"₹ 8,000 /month","₹ 10,000-15,000 /month"
2,Content Development (Mathematics),Lawtech,Work from home,Immediately,"₹ 8,000 /month","₹ 6,000-8,000 /month"
3,Arithmetic & Mental Ability Content Curation (...,Lawtech,Work from home,Immediately,"₹ 8,000 /month","₹ 6,000-8,000 /month"
4,Full Stack Data Engineering,Blackcoffer,Work from home,Immediately,"₹ 8,000 /month","₹ 10,000-12,000 /month"
5,Machine Learning,Techvolt Software Private Limited,Coimbatore,Immediately,"₹ 8,000 /month","₹ 6,000 /month"
6,Machine Learning,K4 Media & Technologies,Work from home,Immediately,"₹ 8,000 /month","₹ 10,000 /month"
7,Business Analytics,Rest The Case Services Private Limited,Pune,Immediately,"₹ 8,000 /month","₹ 10,000 /month"
8,Data Science - Content Writing Volunteer,Earth5R,Work from home,Immediately,"₹ 8,000 /month",Unpaid
9,Business Analytics,Conscript HR Advisors Private Limited,Work from home,Immediately,"₹ 8,000 /month","₹ 1,000 /month"
10,Business Analytics,Brain Wave AI Solutions,Work from home,Immediately,"₹ 8,000 /month","₹ 6,500 /month"
11,Data & Reporting,Growify Digital,Delhi,Immediately,"₹ 8,000 /month","₹ 10,000-15,000 /month"
12,Social Sector Marketing,Pawzz,Work from home,Immediately,"₹ 8,000 /month","₹ 1,500-10,000 lump sum"
13,Artificial Intelligence (AI),Coding Junior,Work from home,Immediately,"₹ 8,000 /month","₹ 2,000 /month"
14,Data Analytics,Primary Healthtech,Guwahati,Immediately,"₹ 8,000 /month","₹ 5,000-10,000 /month"
15,Business Analytics,Isourse,Delhi,Immediately,"₹ 8,000 /month","₹ 20,000 /month"
16,Machine Learning,MELE (Make Engineers Life Easy),Work from home,Immediately,"₹ 8,000 /month","₹ 1,000 /month + Incentives"
17,Artificial Intelligence (AI),Asynchron Labs,Work from home,Immediately,"₹ 8,000 /month","₹ 12,000-18,000 /month"
18,Python Development,ALGOTRAK Private Limited,Work from home,Immediately,"₹ 8,000 /month","₹ 15,000 /month"
19,Quant Research,Newberry Group,Mumbai,Immediately,"₹ 8,000 /month","₹ 10,000-12,000 /month"
20,Data Science,Neoperk Technologies Private Limited,Mumbai ...,Immediately,"₹ 8,000 /month","₹ 5,000 /month"
21,Data Analyst,PlayTheory Labs,Work from home,Immediately,"₹ 8,000 /month","₹ 5,000 /month"
22,Artificial Intelligence (AI),Ostello India Private Limited,Work from home,Immediately,"₹ 8,000 /month","₹ 8,000-12,000 /month"
23,Software Development,Pathbeat.in,Work from home,Immediately,"₹ 8,000 /month","₹ 15,000-25,000 /month"
24,Artificial Intelligence (AI),Pawzz,Work from home,Immediately,"₹ 8,000 /month","₹ 10,000-12,000 /month"
25,Research Analyst,Factacy.Ai,Gurgaon,Immediately,"₹ 8,000 /month","₹ 15,000 /month"
26,Machine Learning & AI,Sidhe Petrochemical Private Limited,"Delhi, Noida",Immediately,"₹ 8,000 /month","₹ 7,000-20,000 /month"
27,Business Analytics,DeepThought Edutech Ventures Private Limited,Hyderabad,Immediately,"₹ 8,000 /month","₹ 19,000 /month"
28,Data Analytics,Infinite Creations Private Limited,Delhi,Immediately,"₹ 8,000 /month","₹ 5,000-10,000 /month"
29,Data Analytics,Vedasya Engineering Solutions Private Limited,Hyderabad,Immediately,"₹ 8,000 /month","₹ 10,000 /month"
30,Data Analytics,Futurlytic Private Limited,Bangalore,Immediately,"₹ 8,000 /month","₹ 25,000 /month"
31,Web Scrapping,Medius Technologies Private Limited,Mumbai ...,Immediately,"₹ 8,000 /month","₹ 6,500 /month"
32,Generative AI - Machine Learning,Pianalytix Edutech Private Limted,Work from home,Immediately,"₹ 8,000 /month","₹ 20,000 /month"
33,Human Resources (Data Science),Pianalytix Edutech Private Limted,Work from home,Immediately,"₹ 8,000 /month","₹ 10,000 /month"
34,Backend & ML Development,COSGrid Systems Private Limited,Chennai,Immediately,"₹ 8,000 /month","₹ 15,000-25,000 /month"
35,Data Science,Blackcoffer,Work from home,Immediately,"₹ 8,000 /month","₹ 10,000-12,000 /month"
36,Machine Learning,Buddha Education Association Incorporation,"Surat, Bangalore, Bhopal, Mumbai, Jaipur, Nagp...",Immediately,"₹ 8,000 /month","₹ 25,000 /month"
37,Big Data,Blismos Solutions Private Limited,Bangalore,Immediately,"₹ 8,000 /month","₹ 2,000 /month"
38,Data Analytics,Medius Technologies Private Limited,Mumbai,Immediately,3 Months,"₹ 8,000 /month"
39,Data Analytics,Medius Technologies Private Limited,Mumbai,Immediately,3 Months,"₹ 8,000 /month"